package com.intetics.organizerbot.context;

public enum Context {
    MAIN_MENU,
    ADD_CLASS_CHOOSE_SUBJECT,
    ADD_CLASS_CHOOSE_DATE_OR_DAY,
    ADD_CLASS_CHOOSE_DAY,
    ADD_CLASS_CHOOSE_DATE,
    ADD_CLASS_CHOOSE_TIME,
    ADD_CLASS_CHOOSE_TYPE,
    ADD_CLASS_CHOOSE_ROOM,
    ADD_CLASS_CHOOSE_PROFESSOR,
    SHOW_TIMETABLE
//    ADD_EVENT_CHOOSE_DATE,
//    ADD_EVENT_CHOOSE_TIME,
//    ADD_EVENT_CHOOSE_DESCRIPTION
//    ADD_SUBJECT,
//    REMOVE_SUBJECT,
}
