package com.intetics.organizerbot.entities.auto;

import java.time.LocalDate;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.intetics.organizerbot.entities.Subject;
import com.intetics.organizerbot.entities.Users;

/**
 * Class _Day was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Day extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String DAY_ID_PK_COLUMN = "DAY_ID";

    public static final Property<LocalDate> DATE = Property.create("date", LocalDate.class);
    public static final Property<String> DAY_OF_WEEK = Property.create("dayOfWeek", String.class);
    public static final Property<List<Subject>> SUBJECTS = Property.create("subjects", List.class);
    public static final Property<Users> USERS = Property.create("users", Users.class);

    public void setDate(LocalDate date) {
        writeProperty("date", date);
    }
    public LocalDate getDate() {
        return (LocalDate)readProperty("date");
    }

    public void setDayOfWeek(String dayOfWeek) {
        writeProperty("dayOfWeek", dayOfWeek);
    }
    public String getDayOfWeek() {
        return (String)readProperty("dayOfWeek");
    }

    public void addToSubjects(Subject obj) {
        addToManyTarget("subjects", obj, true);
    }
    public void removeFromSubjects(Subject obj) {
        removeToManyTarget("subjects", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Subject> getSubjects() {
        return (List<Subject>)readProperty("subjects");
    }


    public void setUsers(Users users) {
        setToOneTarget("users", users, true);
    }

    public Users getUsers() {
        return (Users)readProperty("users");
    }


}
