package com.intetics.organizerbot.entities.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.intetics.organizerbot.entities.Lesson;

/**
 * Class _Professors was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Professors extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String PROFESSOR_ID_PK_COLUMN = "PROFESSOR_ID";

    public static final Property<String> PROFESSOR_NAME = Property.create("professorName", String.class);
    public static final Property<List<Lesson>> LESSONS = Property.create("lessons", List.class);

    public void setProfessorName(String professorName) {
        writeProperty("professorName", professorName);
    }
    public String getProfessorName() {
        return (String)readProperty("professorName");
    }

    public void addToLessons(Lesson obj) {
        addToManyTarget("lessons", obj, true);
    }
    public void removeFromLessons(Lesson obj) {
        removeToManyTarget("lessons", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Lesson> getLessons() {
        return (List<Lesson>)readProperty("lessons");
    }


}
