package com.intetics.organizerbot.entities.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.intetics.organizerbot.entities.Lesson;
import com.intetics.organizerbot.entities.Users;

/**
 * Class _Subject was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Subject extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String SUBJECT_ID_PK_COLUMN = "SUBJECT_ID";

    public static final Property<String> SUBJECT_TITLE = Property.create("subjectTitle", String.class);
    public static final Property<Integer> USER_ID = Property.create("userId", Integer.class);
    public static final Property<List<Lesson>> LESSONS = Property.create("lessons", List.class);
    public static final Property<Users> USER = Property.create("user", Users.class);

    public void setSubjectTitle(String subjectTitle) {
        writeProperty("subjectTitle", subjectTitle);
    }
    public String getSubjectTitle() {
        return (String)readProperty("subjectTitle");
    }

    public void setUserId(int userId) {
        writeProperty("userId", userId);
    }
    public int getUserId() {
        Object value = readProperty("userId");
        return (value != null) ? (Integer) value : 0;
    }

    public void addToLessons(Lesson obj) {
        addToManyTarget("lessons", obj, true);
    }
    public void removeFromLessons(Lesson obj) {
        removeToManyTarget("lessons", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Lesson> getLessons() {
        return (List<Lesson>)readProperty("lessons");
    }


    public void setUser(Users user) {
        setToOneTarget("user", user, true);
    }

    public Users getUser() {
        return (Users)readProperty("user");
    }


}
